tokenlite_app/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middle-ware group. Now create something great!
|
*/
if (application_installed()) {
    Route::get('/install/final', function () {
        return redirect('/');
    });
}

// Twitter
//Route::get('twitterUserTimeLine', 'TwitterController@twitterUserTimeLine');
//Route::post('tweet', ['as'=>'post.tweet','uses'=>'TwitterController@tweet']);


// Handle Main / Route
Route::get('/', 'Auth\LoginController@checkLoginState')->name('home');
Route::get('/locale', 'PublicController@set_lang')->name('language');

Route::get('/bounty', 'User\BountyController@index')->name('bounty');
Route::get('bounty/socialUsername', 'User\BountyController@socialUsername')->name('bounty.socialUsername');
Route::get('bounty/socialFollowers', 'User\BountyController@socialFollowers')->name('bounty.socialFollowers');

// Authenticates Routes
Route::get('/auth/{service}', 'Auth\SocialAuthController@redirect')->name('social.login');
Route::get('/auth/{service}/callback', 'Auth\SocialAuthController@callback')->name('social.login.callback');
Route::post('/auth/social/register', 'Auth\SocialAuthController@register')->name('social.register');

// Authenticates Routes
Auth::routes();
Route::get('verify/', 'Auth\VerifyController@index')->name('verify');
Route::get('verify/resend', 'Auth\VerifyController@resend')->name('verify.resend');
Route::get('verify/{id}/{token}', 'Auth\VerifyController@verify')->name('verify.email');
Route::get('verify/success', 'Auth\LoginController@verified')->name('verified');
Route::get('register/success', 'Auth\LoginController@registered')->name('registered');
Route::any('log-out', 'Auth\LoginController@logout')->name('log-out');

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

// Google 2FA Routes
Route::get('/login/2fa', 'Auth\SocialAuthController@show_2fa_form')->middleware('auth')->name('auth.2fa');
Route::get('/login/2fa/reset', 'Auth\SocialAuthController@show_2fa_reset_form')->name('auth.2fa.reset');
Route::post('/login/2fa/reset', 'Auth\SocialAuthController@reset_2fa');
Route::post('/login/2fa', function () {
    return redirect()->route('home');
})->middleware(['auth', 'g2fa']);

// if(is_maintenance()){
Route::get('admin/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin/login', 'Auth\LoginController@login');
Route::post('admin/logout', 'Auth\LoginController@logout')->name('admin.logout');
Route::get('admin/login/2fa', 'Auth\SocialAuthController@show_2fa_form')->middleware('auth')->name('admin.auth.2fa');
Route::post('admin/login/2fa', function () {
    return redirect()->route('home');
})->middleware(['auth', 'g2fa']);
// }

// User Routes
Route::prefix('user')->middleware(['auth', 'user', 'verify_user', 'g2fa'])->name('user.')->group(function () {
    Route::get('/', 'User\UserController@index')->name('home');
    Route::get('/account', 'User\UserController@account')->name('account');
    Route::get('/account/activity', 'User\UserController@account_activity')->name('account.activity');
    Route::get('/contribute', 'User\TokenController@index')->name('token');
    Route::get('/contribute/cancel/{gateway?}', 'User\TokenController@payment_cancel')->name('payment.cancel');
    Route::get('/transactions', 'User\TransactionController@index')->name('transactions');
    Route::get('/kyc', 'User\KycController@index')->name('kyc');
    Route::get('/kyc/application', 'User\KycController@application')->name('kyc.application');
    Route::get('/kyc/application/view', 'User\KycController@view')->name('kyc.application.view');
    Route::get('/kyc-list/documents/{file}/{doc}', 'User\KycController@get_documents')->middleware('ico')->name('kycs.file');
    Route::get('/password/confirm/{token}', 'User\UserController@password_confirm')->name('password.confirm');
    // Referral v1.0.3 > v1.1.1
    Route::get('/referral', 'User\UserController@referral')->name('referral');
    // My Token v1.1.2
    Route::get('/account/balance', 'User\UserController@mytoken_balance')->name('token.balance');
    // Bounty v1.0.0
    // Generate Token
    Route::get('/generate_token', 'User\TokenController@generate_child_token')->name('generate_token');

    Route::get('/facebook/callback', 'User\BountyController@facebook_callback')->name('facebook.callback');

    // User Ajax Request
    Route::name('ajax.')->prefix('ajax')->group(function () {
        Route::post('/account/wallet-form', 'User\UserController@get_wallet_form')->name('account.wallet');
        Route::post('/account/update', 'User\UserController@account_update')->name('account.update')->middleware('demo_user');
        Route::post('/contribute/access', 'User\TokenController@access')->name('token.access');
        Route::post('/contribute/payment', 'User\TokenController@payment')->name('payment');

        Route::post('/transactions/delete/{id}', 'User\TransactionController@destroy')->name('transactions.delete')->middleware('demo_user');
        Route::post('/transactions/view', 'User\TransactionController@show')->name('transactions.view');
        Route::post('/kyc/submit', 'User\KycController@submit')->name('kyc.submit');
        Route::post('/account/activity', 'User\UserController@account_activity_delete')->name('account.activity.delete')->middleware('demo_user');


        Route::post('/bounty/submit', 'User\BountyController@submit')->name('bounty.submit');

    });
});


Route::prefix('admin')->middleware(['auth', 'admin', 'g2fa', 'ico'])->name('admin.')->group(function () {
    Route::get('/', 'Admin\AdminController@index')->name('home');
    Route::any('/system-info', 'Admin\AdminController@system_info')->name('system');
    Route::any('/apps-register', 'Admin\SettingController@app_register')->name('niolite');
    Route::get('/profile', 'Admin\AdminController@profile')->middleware('ico')->name('profile');
    Route::get('/profile/activity', 'Admin\AdminController@activity')->middleware('ico')->name('profile.activity');
    Route::get('/password/confirm/{token}', 'Admin\AdminController@password_confirm')->name('password.confirm');
    Route::get('/transactions/{state?}', 'Admin\TransactionController@index')->middleware('ico')->name('transactions');
    Route::get('/stages/settings', 'Admin\IcoController@settings')->middleware('ico')->name('stages.settings');
    Route::get('/globalequity/settings', 'Admin\GlobalEquityController@settings')->name('equity.settings');
    Route::get('/pages', 'Admin\PageController@index')->middleware('ico')->name('pages');
    Route::get('/settings', 'Admin\SettingController@index')->middleware(['ico', 'super_admin'])->name('settings');
    Route::get('/settings/email', 'Admin\EmailSettingController@index')->middleware(['ico', 'super_admin'])->name('settings.email');
    Route::get('/settings/referral', 'Admin\SettingController@referral_setting')->middleware(['ico', 'super_admin'])->name('settings.referral'); // v1.1.2
    Route::get('/settings/rest-api', 'Admin\SettingController@api_setting')->middleware(['ico', 'super_admin'])->name('settings.api'); // v1.0.6
    Route::get('/payment-methods', 'Admin\PaymentMethodController@index')->middleware(['ico', 'super_admin'])->name('payments.setup');
    Route::get('/payment-methods/edit/{slug}', 'Admin\PaymentMethodController@edit')->middleware(['ico', 'super_admin'])->name('payments.setup.edit');
    Route::get('/stages', 'Admin\IcoController@index')->middleware('ico')->name('stages');
    Route::get('/stages/{id}', 'Admin\IcoController@edit_stage')->middleware('ico')->name('stages.edit');
    Route::get('/users/{role?}', 'Admin\UsersController@index')->middleware('ico')->name('users'); //v1.1.0
    Route::get('/users/wallet/change-request', 'Admin\UsersController@wallet_change_request')->middleware('ico')->name('users.wallet.change');
    Route::get('/kyc-list/{status?}', 'Admin\KycController@index')->middleware('ico')->name('kycs'); //v1.1.0
    Route::get('/kyc-list/documents/{file}/{doc}', 'Admin\KycController@get_documents')->middleware('ico')->name('kycs.file');
    Route::get('/transactions/view/{id}', 'Admin\TransactionController@show')->name('transactions.view');
    Route::get('/users/{id?}/{type?}', 'Admin\UsersController@show')->name('users.view');
    Route::get('/kyc/view/{id}/{type}', 'Admin\KycController@show')->name('kyc.view');
    Route::get('/pages/{slug}', 'Admin\PageController@edit')->middleware('ico')->name('pages.edit');
    Route::get('/export/{table?}/{format?}', 'ExportController@export')->middleware(['ico', 'demo_user', 'super_admin'])->name('export'); // v1.1.0
    Route::get('/languages', 'Admin\LanguageController@index')->middleware(['ico'])->name('lang.manage'); // v1.1.3
    Route::get('/languages/translate/{code}', 'Admin\LanguageController@translator')->middleware(['ico'])->name('lang.translate'); // v1.1.3

    Route::get('/bounty/setting', 'Admin\BountyController@index')->name('bounty.setting');

    Route::get('/bounty/stage', 'Admin\BountyController@stage')->name('bounty.stages');
    Route::get('/bounty/stages/{id}', 'Admin\BountyController@edit_stage')->name('bounty.stages.edit');
    Route::get('/bounty/overview', 'Admin\BountyController@bounty_overview')->name('bounty.stages.overview');
    // Route::get('/bounty/delete', 'Admin\BountyController@delete')->name('bounty.delete');

    /* Admin Ajax Route */
    Route::name('ajax.')->prefix('ajax')->middleware(['ico'])->group(function () {
        Route::post('/users/view', 'Admin\UsersController@status')->name('users.view')->middleware('demo_user');

tokenlite_app/resources/views/modals/adjustment_token.blade.php
<div class="modal fade" id="adjustment" tabindex="-1">
    <div class="modal-dialog modal-dialog-md modal-dialog-centered">
        <div class=" sd modal-content">
            <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close"><em class="ti ti-close"></em></a>
            <div class="popup-body popup-body-md">
                <h3 class="popup-title">Approve Transaction of {{$trnx->tnx_id }}</h3>

                <form action="javascript:void(0)" method="POST" autocomplete="off" id="adjust_token_cal">
                    @csrf
                    <input class="input-bordered" type="hidden" name="tnx_id" value="{{ $trnx->id}}">
                    <input class="input-bordered" type="hidden" name="req_type" value="approved">
                    <div class="row">
                        <div class="col-12">
                             <p>User requested to purchase <strong>{{$trnx->total_tokens.' '.token_symbol()}}</strong> Token and payment amount <strong>{{ to_num($trnx->amount, 'max').' '.strtoupper($trnx->currency) }}</strong>. Please update received amount accrodingly if you received less or more than payment amount.</p>
                             <div class="gaps-1-5x"></div>
                         </div>
                         <div class="col-sm-6">
                            <div class="input-item input-with-label w-sm-60">
                                <label class="input-item-label">Received Amount <strong class="h5 text- text-info text-uppercase">({{$trnx->currency}})</strong></label>
                                <input class="input-bordered" required="" id="receive_amount" type="number" value="{{ to_num($trnx->amount, 'max') }}" name="receive_amount">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="input-item input-with-label w-sm-60">
                                <label class="input-item-label">Token to adjust</label>
                                <input class="input-bordered" type="number" name="total_tokens" id="total_tokens" value="{{ $trnx->total_tokens }}" readonly>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="input-item">
                                <input type="checkbox" disabled="" value="1" class="chk_adjust input-checkbox input-checkbox-md" id="token_amount_adjust">
                                <label for="token_amount_adjust">Check this to confirm adjusted token.</label>
                            </div>
                        </div>
                    </div>
                    <div class="gaps-1x"></div>
                    <button type="submit" class="btn btn-md btn-auto btn-primary tnx-action" data-type="approved" data-id="{{ $trnx->id }}">
                        <span><em class="far fa-check-square"></em><span>Approve</span></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function($) {

    //adjust and calculate on field
    var adjust_form = $('#adjust_token_cal'), receive_amount = $('#receive_amount'), adjust_token = $('#total_tokens'), $chk = adjust_form.find('.chk_adjust'),
        rec_amount = adjust_form.find(receive_amount).val();
    $('#adjustment').find('.tnx-action').data('_amount',rec_amount);

    adjust_form.find(":input").bind('keyup change', function() {

        var rec_amount = adjust_form.find(receive_amount).val(),
        adj_token = adjust_form.find(adjust_token).val(),
        tnx_id = {!! $trnx->id !!},
        currency = '{!! $trnx->currency !!}',
        currency_rate = {!! $trnx->currency_rate !!},
        bonus_on_base = {!! $trnx->bonus_on_base !!},
        bonus_on_token = {!! $trnx->bonus_on_token !!},
        old_amount = {!! $trnx->total_tokens !!} - bonus_on_token -bonus_on_base,
        all_currency_rate = {!! $trnx->all_currency_rate !!};

        $_token = parseInt(rec_amount / currency_rate);
        _base_bonus = parseInt((bonus_on_base / old_amount )*$_token);
        _token_bonus = parseInt((bonus_on_token / old_amount )*$_token);
        $_adjusted = $_token+ _base_bonus + _token_bonus;
        adjust_token.val($_adjusted);

        if(rec_amount <=0){
            $chk.is(':checked')?$chk.click():'';
            $chk.attr('disabled', true);
        }
        else{
            $chk.removeAttr('disabled');
        }

        var chk_adjust = (adjust_form.find('.chk_adjust').is(':checked')) ? 1:0;

        $('#adjustment').find('.tnx-action').data('_b_bonus',_base_bonus).data('_t_bonus',_token_bonus).data('_adjusted',$_adjusted).data('_amount',rec_amount).data('_chk',chk_adjust).data('token', $_token);

    });

})(jQuery);
</script>

tokenlite_app/resources/views/modals/payment-amount.blade.php
<a href="#" class="modal-close" data-dismiss="modal"><em class="ti ti-close"></em></a>

<div class="popup-body">
    <h2 class="popup-title">Buy {{ strtoupper(token_symbol()) }} Tokens</h2>
    <div class="tranx-payment-details">
        <form action="{{ route('user.ajax.token.access') }}" method="POST" id="token_payment">
            @csrf
            <input type="hidden" name="currency" id="pay_currency" value="{{ $currency }}">
            <input type="hidden" name="req_type" id="pay_currency" value="{{ $get }}">

            <div class="gaps-1x"></div>
            <div class="payment-input">
                <input name="token_amount" placeholder="Enter number of token" class="input-bordered token-number" type="number" id="token-number" value="" min="{{ active_stage()->min_purchase }}" max="{{ active_stage()->max_purchase }}"><span class="payment-get-cur payment-cal-cur">{{ token_symbol() }}</span>
            </div>
            <div class="gaps-1x"></div>
            <input type="hidden" class="input-checkbox" id="agree" name="agree" value="1">
            <div class="gaps-2x"></div>
            <button type="submit" class="btn  btn-alt btn-primary payment-btn"><span>Proceed<em class="ti-arrow-right"></em></span></button>
            <div class="gaps-3x"></div>
        </form>
    </div>
</div>


<script type="text/javascript">

    (function($) {
        var $_p_form = $('form#token_payment');
        if ($_p_form.length > 0) {
            purchase_form_submit($_p_form);
        }

    })(jQuery);
</script>

tokenlite_app/resources/views/modals/payment-canceled.blade.php
<a href="#" class="modal-close" data-dismiss="modal"><em class="ti ti-close"></em></a>

<div class="popup-body text-center">
    <div class="gaps-2x"></div>
    <div class="pay-status pay-status-error">
        <em class="ti ti-alert danger"></em>
    </div>
    <div class="gaps-2x"></div>
    <h3>{{ __('Oops! Payment Canceled!')}}</h3>
    <p>{!! __('You have canceled your payment. If you continue to have issues, please contact us with order no. :orderid.',[ 'orderid' => '<strong>'.$tnxns->tnx_id.'</strong>']) !!}</p> 
    <div class="gaps-2x"></div>
    <a href="javascript:void(0)" class="btn btn-danger close-modal">{{__('Close')}}</a>  
    <div class="gaps-1x"></div>
</div>

<script type="text/javascript">
    (function($) {
        $('.close-modal, .modal-close').on('click', function(e){
            e.preventDefault();
            var $link = $(this).attr('href');
            $(this).parents('.modal').modal('hide');
            window.location.reload();
        });
    })(jQuery);
</script>

tokenlite_app/resources/views/modals/payment-review.blade.php
<a href="{{ route('user.token') }}" class="modal-close" data-dismiss="modal"><em class="ti ti-close"></em></a>
<div class="popup-body text-center">
    <div class="gaps-2x"></div>
    <div class="pay-status pay-status-success">
        <em class="ti ti-check warning"></em>
    </div>
    <div class="gaps-2x"></div>
    <h3>{{__("We're reviewing your payment.")}}</h3>
    <p>{{__("We'll review your transaction and get back to your within 6 hours. You'll receive an email with the details of your contribution.")}}</p>
    <div class="gaps-2x"></div>
    <a href="{{ route('user.transactions') }}" class="btn btn-primary"><span>{{ __('View Transaction') }}</span></a>
    <div class="gaps-1x"></div>
</div>

tokenlite_app/resources/views/modals/payment-success.blade.php
<a href="{{ route('user.transactions') }}" class="modal-close" data-dismiss="modal"><em class="ti ti-close"></em></a>
<div class="popup-body text-center">
    <div class="gaps-2x"></div>
    <div class="pay-status pay-status-success">
        <em class="ti ti-check success"></em>
    </div>
    <div class="gaps-2x"></div>
    <h3>{{__('We’re received your payment.')}}</h3>
    <p>{{__('Thank you for your contribution, we are added the token to your account balance.')}}</p>
    <div class="gaps-2x"></div>
    <a href="{{ route('user.transactions') }}" class="btn btn-primary"><span>{{__('View Transaction')}}</span></a>
    <div class="gaps-1x"></div>
</div>

tokenlite_app/resources/views/modals/user_referrals.blade.php
<div class="modal fade" id="user-activities" tabindex="-1">
    <div class="modal-dialog modal-dialog-lg modal-dialog-centered">
        <div class="modal-content">
            <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close"><em class="ti ti-close"></em></a>
            <div class="popup-body popup-body-lg">
                <h3 class="popup-title">Referral User Lists 
                    <em class="ti ti-angle-right"></em> <small class="user-id">{{ set_id($user->id) }}</small>
                </h3>
                <ul class="data-details-alt">
                    {{-- @dd($refered) --}}
                    @forelse($refered as $refer)
                    <li class="text-dark row no-gutters justify-content-between">
                        <div class="col-12 col-lg order-lg-last">
                            <span class="fs-12 text-light data-details-date">Joined: {{ _date($refer->created_at) }}</span>
                        </div>
                        <div class="col-md col-6"><strong class="text-dark">{{ set_id($refer->id).' - '.$refer->name }}</strong></div>
                        <div class="col-md col-6 text-right text-md-left"><a target="_blank" href="{{ route('admin.users.view', [$refer->id, 'details'] ) }}">View User</a></div>
                        <div class="col-md col-sm-6">
                            @if(isset($refer->refer_to) && $refer->refer_to > 0) 
                            <a href="javascript:void(0)" data-uid="{{ $refer->id }}" data-type="referrals" class="user-form-action user-action"><em class="fas fa-search-plus"></em> {{ $refer->refer_to . ' Contributors' }}</a>
                            @else 
                            ~
                            @endif
                        </div>
                    </li>
                    @empty
                    <li><div class="col-md col-sm-6"><strong class="text-dark">No one join yet!</strong></div></li>
                    @endforelse
                </ul>
            </div>
        </div>
    </div>
</div>

tokenlite_app/resources/views/modals/user_transactions.blade.php
<div class="modal fade" id="user-transaction" tabindex="-1">
    <div class="modal-dialog modal-dialog-lg modal-dialog-centered">
        <div class="modal-content">
            <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close"><em class="ti ti-close"></em></a>
            <div class="popup-body popup-body-lg">
                <h3 class="popup-title">All Transaction By <em class="ti ti-angle-right"></em> <small class="tnx-id">{{ set_id($user->id) }}</small></h3>
                <ul class="data-details-alt">
                    @forelse($transactions as $tnx)
                    <li class="text-dark row no-gutters justify-content-between">
                        <div class="col-12 col-lg order-lg-last"><small class="text-light data-details-date">{{ _date($tnx->tnx_time) }}</small></div>
                        <div class="col-md col-sm-6"><strong class="text-dark">{{ ucfirst($tnx->tnx_type) }}</strong></div>
                        <div class="col-md col-sm-6"><span class="text-dark">{{ get_stage($tnx->stage, 'name') }}</span></div>
                        <div class="col-md col-sm-6 order-sm-2 order-md-1"><span class="text-light"><a href="{{ route('admin.transactions.view', $tnx->id) }}" target="_blank">{{ $tnx->tnx_id }}</a></span></div>
                        <div class="col-md col-sm-6 order-sm-1 order-md-2"><strong class="text-dark">{{ (starts_with($tnx->total_tokens, '-') ? '' : '+').$tnx->total_tokens }}</strong></div>
                        <div class="col-md col-sm-6 order-sm-3"><span class="text-light small">{{ to_num($tnx->amount, 'max').' '.strtoupper($tnx->currency) }} <em class="fas fa-info-circle fs-11" data-toggle="tooltip" data-placement="bottom" title="1 {{ token('symbol') }} = {{ $tnx->currency_rate.' '.strtoupper($tnx->currency) }}"></em></span></div>
                    </li>
                    @empty
                    <li><div class="col-md col-sm-6"><strong class="text-dark">No approved transaction found!</strong></div></li>
                    @endforelse
                </ul>{{-- .data-details --}}
            </div>
        </div>
    </div>
</div>

tokenlite_app/resources/views/modals/user_wallet.blade.php
@php
$user = auth()->user();
$wallets = token_wallet();

$notes = '<div class="note note-plane note-danger"><em class="fas fa-info-circle"></em><p>'.__("DO NOT USE your exchange wallet address OR if you don't have a private key of the your address. You WILL NOT receive your token and WILL LOSE YOUR FUNDS if you do.").'</p></div>';

$wallet_count = (!empty($wallets)) ? count($wallets) : 0;

$wallet_type_selection = ''; $is_single_wallet = false; $wallet_name = '';
$is_disable = ($user->walletType != NULL) ? ' disabled' : '';
$no_wallet = ($wallet_count >= 1) ? false : true;

if ($wallet_count >= 2) {
    foreach ($wallets as $wname => $wlabel) {
        $wallet_type_selection .= '<option '.($user->walletType == $wname ? 'selected ' : '').'value="'.$wname.'">'.$wlabel.'</option>';
    }
} elseif($wallet_count==1) {
    $wallet_type_selection .=  '<input type="hidden" name="wallet_name" value="'.strtolower(array_values($wallets)[0]).'">';
    $is_single_wallet = true;
    $wallet_name = array_values($wallets)[0].' ';
}

// dd($wallet, $wallets);
@endphp
<div class="modal fade" id="add-wallet" tabindex="-1">
    <div class="modal-dialog modal-dialog-md modal-dialog-centered">
        <div class="modal-content">
            <a href="#" class="modal-close" data-dismiss="modal" aria-label="Close"><em class="ti ti-close"></em></a>
            <div class="popup-body popup-body-md">
                <h4 class="popup-title">{{__('Wallet Address')}}</h4>
                <p>{!!__('In order to receive your :SYMBOL token, please select your wallet address and you have to put the address below input box. You will receive :SYMBOL token to this address after the token sale end.', ['symbol' => '<strong>'.token_symbol().'</strong>' ]) !!}</p>
                <div class="gaps-1x"></div>
                @if(!$no_wallet)
                    @if(has_wallet())
                    <ul class="nav nav-tabs"  role="tablist">
                        <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#wallet">{{__('Current Wallet')}}</a></li>
                        <li class="nav-item"><a class="nav-link" data-toggle="tab" href="#request">{{__('Request for change')}}</a></li>
                    </ul>
                    @endif
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="wallet">
                            <form class="validate-modern _reload" action="{{ route('user.ajax.account.update') }}" method="POST" id="nio-user-wallet-update" autocomplete="off">
                                @csrf
                                <input type="hidden" name="action_type" value="wallet">
                                @if ($is_single_wallet==true)
                                {!! $wallet_type_selection !!}
                                @else
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="input-item input-with-label">
                                            <label for="swalllet" class="input-item-label">{{ (!has_wallet() ? __('Select Wallet') : __('Wallet Type')) }}</label>
                                            <select class="select-bordered select select-block" name="wallet_name" id="swalllet"{{ $is_disable }}>
                                                {!! $wallet_type_selection !!}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                @endif
                            <div class="input-item input-with-label">
                                <label for="token-address" class="input-item-label">{{ (!has_wallet() ? __('Enter your :Name wallet address', ['name' => $wallet_name]) : __(':Name Wallet Address for receiving token', ['name' => $wallet_name]) ) }}</label>
                                <div class="input-wrap">
                                    <input class="input-bordered" type="text" id="token-address" name="wallet_address" value="{{ $user->walletAddress }}"{{ $is_disable}} required>
                                </div>
                                <span class="input-note">{{__('Note:')}} {{ get_setting('token_wallet_note') }}</span>
                            </div>{{-- .input-item --}}
                            @if(!has_wallet())
                            {!! $notes !!}
                            <div class="gaps-3x"></div>
                            <div class="d-sm-flex justify-content-between align-items-center">
                                <button type="submit" class="btn btn-primary"><span>{{__('Add Wallet')}}</span></button>
                            </div>
                            @endif
                        </form>{{-- form --}}
                    </div>
                    @if(has_wallet())
                    <div class="tab-pane fade" id="request">
                        <form class="validate-modern _reload" action="{{ route('user.ajax.account.update') }}" method="POST" id="nio-user-wallet-request" autocomplete="off">
                            @csrf
                            <input type="hidden" name="action_type" value="wallet_request">
                            @if ($is_single_wallet==true)
                            {!! $wallet_type_selection !!}
                            @else
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="input-item input-with-label">
                                        <label for="swallletr" class="input-item-label">{{ (!has_wallet() ? __('Select Wallet') : __('Wallet Type')) }}</label>
                                        <select class="select-bordered select select-block" name="wallet_name" id="swallletr">
                                            {!! $wallet_type_selection !!}
                                        </select>
                                    </div>
                                </div>
                            </div>
                            @endif
                            <div class="input-item input-with-label">
                                <label for="token-address2" class="input-item-label">{{ __('Enter your new :Name wallet address', ['name' => $wallet_name]) }}</label>
                                <div class="input-wrap">
                                    <input class="input-bordered" type="text" id="token-address2" name="wallet_address" value="" required>
                                </div>
                                <span class="input-note">{{__('Note:')}} {{ get_setting('token_wallet_note') }}</span>
                            </div>{{-- .input-item --}}
                            {!! $notes !!}
                            <div class="gaps-3x"></div>
                            <div class="d-sm-flex justify-content-between align-items-center">
                                <button type="submit" class="btn btn-primary"><span>{{__('Request for Update Wallet')}}</span></button>
                            </div>
                        </form>{{-- form --}}
                    </div>
                    @endif
                @endif
            </div>
        </div>
    </div>{{-- .modal-content --}}
</div>{{-- .modal-dialog --}}
</div>
{{-- Modal End --}}
<script type="text/javascript">
    (function($) {
        var $nio_user_wallet = $('#nio-user-wallet-update, #nio-user-wallet-request');
        if ($nio_user_wallet.length > 0) { ajax_form_submit($nio_user_wallet, true, 'ti ti-alert', true); }
    })(jQuery);
</script>